### ISSUE TITLE
0.1.14 release: ClockResetError: Out of range timestamp seen

### ISSUE THREAD

**Issue by jester-xbmc** [mutability/mlat-client#1]
Hi,
I'm getting loads of these on 0.1.14 release running on r-pi2 

Sun Jun  7 00:43:28 2015 Unexpected exception on connection to localhost:30005
Traceback (most recent call last):
  File "/usr/lib/python3.2/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.2/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/lib/python3/dist-packages/mlat/client/receiver.py", line 128, in handle_read
    consumed, messages = self.packetize(moredata, self.last_timestamp)
_modes.ClockResetError: Out of range timestamp seen

**Comment by mutability** [comment]
Are you feeding more than one receiver to the client?

**Comment by jester-xbmc** [comment]
No, its a clean pi2 running your fork of dump1090, and the mlat client

**Comment by mutability** [comment]
Can you try 0.1.15, just released? http://repo.mutability.co.uk/raspbian/pool/rpi/m/mlat-client/mlat-client_0.1.15_armhf.deb

It doesn't have anything that will fix the underlying problem but it adds some debugging to the ClockResetError message so that hopefully I can see what's going on.

**Comment by jester-xbmc** [comment]
Updated, after reboot, it runs for about 2 minutes and then:
Sun Jun  7 12:51:00 2015 Unexpected exception on connection to localhost:30005
Traceback (most recent call last):
  File "/usr/lib/python3.2/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.2/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/lib/python3/dist-packages/mlat/client/receiver.py", line 128, in handle_read
    consumed, messages = self.packetize(moredata, self.last_timestamp)
_modes.ClockResetError: Out of range timestamp seen (last 1094766990, now 3725160)
Sun Jun  7 12:51:00 2015 Lost connection to localhost:30005

**Comment by mutability** [comment]
Ok - if you could keep an eye on it for a bit and report the values from a few more reset errors that'd be great.

**Comment by jester-xbmc** [comment]
Update, playing around, I removed --modeac from the EXTRA_ARGS and now its running fine ??

**Comment by jester-xbmc** [comment]
For debug, here are more errors:

Sun Jun  7 12:57:13 2015 Unexpected exception on connection to localhost:30005
Traceback (most recent call last):
  File "/usr/lib/python3.2/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.2/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/lib/python3/dist-packages/mlat/client/receiver.py", line 128, in handle_read
    consumed, messages = self.packetize(moredata, self.last_timestamp)
_modes.ClockResetError: Out of range timestamp seen (last 5570345214, now 214589088)
Sun Jun  7 12:57:13 2015 Lost connection to localhost:30005
Sun Jun  7 12:57:13 2015 Reconnecting in 30.0 seconds
Sun Jun  7 12:57:44 2015 Input connected to localhost:30005
Sun Jun  7 12:57:44 2015 Unexpected exception on connection to localhost:30005
Traceback (most recent call last):
  File "/usr/lib/python3.2/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.2/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/lib/python3/dist-packages/mlat/client/receiver.py", line 128, in handle_read
    consumed, messages = self.packetize(moredata, self.last_timestamp)
_modes.ClockResetError: Out of range timestamp seen (last 5935545114, now 895738332)
Sun Jun  7 12:57:44 2015 Lost connection to localhost:30005
Sun Jun  7 12:57:44 2015 Reconnecting in 30.0 seconds
Sun Jun  7 12:58:14 2015 Input connected to localhost:30005
Sun Jun  7 12:58:15 2015 Unexpected exception on connection to localhost:30005
Traceback (most recent call last):
  File "/usr/lib/python3.2/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.2/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/lib/python3/dist-packages/mlat/client/receiver.py", line 128, in handle_read
    consumed, messages = self.packetize(moredata, self.last_timestamp)
_modes.ClockResetError: Out of range timestamp seen (last 6304498638, now 10627572)

**Comment by jester-xbmc** [comment]
Update, playing around, I removed --modeac from the EXTRA_ARGS and now its running fine ??

**Comment by mutability** [comment]
Aha! Ok, that's useful to know. I don't run with 2MHz / --modeac here so that's probably why I don't see it. Let me investigate..

**Comment by mutability** [comment]
Can't reproduce it here with 2MHz and --modeac. Which version of dump1090-mutability exactly are you using?

**Comment by jester-xbmc** [comment]
dump1090-mutability v1.14

**Comment by jester-xbmc** [comment]
Current config (lat/long redacted)
START_DUMP1090="yes"
DUMP1090_USER="dump1090"
LOGFILE="/var/log/dump1090-mutability.log"
DEVICE=""
GAIN="max"
PPM="24"
OVERSAMPLE="no"
PHASE_ENHANCE="yes"
FIX_CRC="yes"
AGGRESSIVE="yes"
LAT="52XXX"
LON="4XXX"
MAX_RANGE="500"
HTTP_PORT="0"
RAW_INPUT_PORT="0"
RAW_OUTPUT_PORT="0"
SBS_OUTPUT_PORT="30003"
BEAST_INPUT_PORT="0"
BEAST_OUTPUT_PORT="30005"
FATSV_OUTPUT_PORT="0"
NET_HEARTBEAT="120"
NET_OUTPUT_SIZE="500"
NET_OUTPUT_INTERVAL="1"
NET_BUFFER="65536"
NET_BIND_ADDRESS=""
STATS_INTERVAL="7200"
JSON_DIR=""
JSON_INTERVAL="120"
JSON_LOCATION_ACCURACY="exact"
LOG_DECODED_MESSAGES="no"
EXTRA_ARGS=""

**Comment by mutability** [comment]
And it's OK with that config but breaks if you add --modeac?

I have almost the same config on my test system but with AGGRESSIVE="no" and it's not breaking for me. Hmm.

**Comment by jester-xbmc** [comment]
yep, i just changed it again:

Sun Jun  7 13:50:22 2015 Input connected to localhost:30005

Sun Jun  7 13:51:40 2015 Unexpected exception on connection to localhost:30005
Traceback (most recent call last):
  File "/usr/lib/python3.2/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.2/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/lib/python3/dist-packages/mlat/client/receiver.py", line 128, in handle_read
    consumed, messages = self.packetize(moredata, self.last_timestamp)
_modes.ClockResetError: Out of range timestamp seen (last 1098944124, now 2180400)

**Comment by jester-xbmc** [comment]
btw, i just tried the same thing on my other receiver (a pi 1, not 2) same thing:

Sun Jun  7 13:56:33 2015 Unexpected exception on connection to localhost:30005
Traceback (most recent call last):
  File "/usr/lib/python3.2/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.2/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/lib/python3/dist-packages/mlat/client/receiver.py", line 128, in handle_read
    consumed, messages = self.packetize(moredata, self.last_timestamp)
_modes.ClockResetError: Out of range timestamp seen (last 1092622086, now 7741770)
Sun Jun  7 13:56:33 2015 Lost connection to localhost:30005

**Comment by mutability** [comment]
Ok I can reproduce this now, it's something very specific to your settings, I didn't get it happening until I exactly reproduced all your settings. I wonder if it's the heartbeat setting actually..

**Comment by jester-xbmc** [comment]
that would make sense as its at 2 minutes, and thats about how long it takes for it to crash after start up

**Comment by mutability** [comment]
There's a 90 second leeway for "backwards" timestamps so it only starts showing up after dump1090 has been running at least that long (since the timestamps start from zero on restart).

I may not have time to dig into this properly today but now that I can reproduce it should be straightforward enough to fix. Thanks for the detailed report :)

**Comment by jester-xbmc** [comment]
ok, same crash with heartbeat=60 or heartbeat=0 btw.....

**Comment by jester-xbmc** [comment]
i will keep playing to maybe narrow it down, thanks for your work !

**Comment by mutability** [comment]
I tracked this down to a dump1090-mutability bug where it can resend very old (minutes old) Mode A/C messages in some cases.

Workaround: add --net-verbatim to EXTRA_ARGS (this makes dump1090 send _uncorrected_ messages assuming that the recipient will correct CRC errors as needed, and also disables the message queuing that usually happens), or remove --modeac

**Comment by mutability** [comment]
See mutability/dump1090#47

**Comment by jester-xbmc** [comment]
Thanks, with CRC errors you mean on the network stream ? or on the ADS-B/MODE-AC packages? as i'm feeding this mainly to virtual radar server i'm wondering if I have to ask andrew to do CRC corrections ? cheers

**Comment by mutability** [comment]
CRCs on the individual messages received off the air. Usually with --fix or --aggressive, messages with 1 or 2 bit errors will have those errors detected/repaired and the repaired mesages are forwarded. With --net-verbatim, the errors are detected/repaired for internal use, but the original uncorrected message is forwarded (so the recipient can make its own decisions about correction)

I'll have a new mlat-client which works around the bug out sometime today.

**Comment by jester-xbmc** [comment]
understood, thanks, i'll wait for the mlat-client update and then switch --modeac back on.

**Comment by mutability** [comment]
Workaround is in 701cdd7f6825492e3543c87dbeb1e7ef686ca8e3.
Released 0.1.16 that includes this workaround: http://repo.mutability.co.uk/raspbian/pool/rpi/m/mlat-client/mlat-client_0.1.16_armhf.deb
