### ISSUE TITLE
Version for Windows?

### ISSUE THREAD

**Issue by Chrisoo** [mutability/mlat-client#10]
Is it planned version for Windows?
Because truth be told many more people have Windows.

**Comment by mutability** [comment]
It's already cross-platform and, while I don't test under Windows, I've had reports of it running fine there. If something is failing under Windows, please report the specific problems.

**Comment by Chrisoo** [comment]
Where can I download the program to the test?

**Comment by mutability** [comment]
I don't provide a Windows build. You'll need to install Python (and whatever is needed for building extension modules, I don't know the details), and then run setup.py like you would for a normal (non-packaged) install.

**Comment by ke-mccormick** [comment]
You can install latest Python 3.5 version. Then install Visual Studio Community 2015 with Visual C++ and Python Tools. After a reboot you can run from command prompt 'setup.py install' after that is complete you rename mlat-client to mlat-client.py. You then can run mlat-client.py from command prompt. You really should create a batch file mlat-client.bat and add mlat-client.py with all the parameters for easy launching.
