### ISSUE TITLE
Unable to deploy mlat-client with mlat-server

### ISSUE THREAD

**Issue by maxspb89** [mutability/mlat-client#14]
I've got **RTL2838 USB dongle** as a receiver and I try to deploy mlat-server with one client just for test. After that I want to deploy 3 more clients. FlightAware's dump1090-fa takes data from the receiver: **dump1090 params:** `dump1090-fa --interactive --net`
 and outputs it via  port 30005 to mlat-client in beast format. mlat-client is deployed at the same virtual machine with dump1090 and separate to mlat-server. Every time I see about 3 to 7 planes with or without coordinates, so dump1090 receives well. Also I can draw planes with modesmixer2 app, so messages translated through port 30005 are correct.
**mlat-client params:** `mlat-client --input-connect 127.0.0.1:30005 --input-type beast --lat 55.xxx --lon 37.xxx --alt 6 --user maxspb --server 10.10.10.10:9999 --results basestation,listen,8888 --no-udp`
**mlat-server params:** `./mlat-server --client-listen 9999:9999 --work-dir /home/maxspb/work/mlat/mlat-server/work_dir --write-csv csv --basestation-connect 10.10.10.9:8888`
After launch, mlat-client stays for a long time in such state:
```
Tue Nov  8 14:47:30 2016 Handshake complete.
Tue Nov  8 14:47:30 2016   Compression:       zlib2
Tue Nov  8 14:47:30 2016   UDP transport:     disabled
Tue Nov  8 14:47:30 2016   Split sync:        disabled
Tue Nov  8 14:47:30 2016 Input connected to 127.0.0.1:30005
Tue Nov  8 14:47:30 2016 Input format changed to BEAST, 12MHz clock
```
And after that it changes to:
```
Tue Nov  8 15:02:31 2016 Receiver status: connected
Tue Nov  8 15:02:31 2016 Server status:   ready
Tue Nov  8 15:02:31 2016 Receiver:   11.2 msg/s received 1.4 msg/s processed (12%)
Tue Nov  8 15:02:31 2016 Server: 0.0 kB/s from server 0.0kB/s TCP to server 0.0kB/s UDP to server
Tue Nov  8 15:02:31 2016 Aircraft: 0 of 0 Mode S, 0 of 1 ADS-B used
```
So nothing goes to server. Please, help me to trace the problem.
1. Is this about just one client connected to the server?
2. Is this about standart USB-dongle antenna?
3. Something configured in a wrong way?

Yours faithfully, maxspb.
P.S. Sorry for mistakes, I'm not a native english speaker.

**Comment by mutability** [comment]
I don't see a bug here? You won't get any mlat results with a single client.

**Comment by maxspb89** [comment]
Is it normal, that server receives no data? `0.0 kB/s from server 0.0kB/s TCP to server 0.0kB/s UDP to server`. Because it doesn't write anything to csv log. So I have to deploy 4 clients to get the server responce?

**Comment by mutability** [comment]
Yes, that's normal, the server only requests data from the clients that is actually going to be useful, and with one client there is no useful data.

**Comment by maxspb89** [comment]
Thanks. I'll try with more clients. If I will deploy the whole system I'm gonna write a manual to other people )
