### ISSUE TITLE
Mlat-client not compatible with Ubuntu 16 (Raspberry) 

### ISSUE THREAD

**Issue by J-Luc16** [mutability/mlat-client#15]
This is due to Python which is now >3.5 and mlat-client is uninstalled automatically for dependancy issue.
The program may work but refuses to start.

**Comment by mutability** [comment]
How did you build mlat-client? debian/control has:
```
Build-Depends: debhelper(>=8), python3-dev
X-Python3-Version: >= 3.2

Depends: ${shlibs:Depends}, ${python3:Depends}, ${misc:Depends}, adduser
```
so it should be fine so long as you built it on the system you want to run it on.

**Comment by J-Luc16** [comment]
Someone built it for me... but it seems that it was badly done :-/

I have successfully compiled & installed under Ubuntu 16 but the process quits and I do not understand why. It's sad because it worked on 15.04.

**Comment by jthawkes** [comment]
try this  (it installs piaware and the mlat client)
sudo apt-get install build-essential debhelper tcl8.5-dev autoconf python3-dev python-virtualenv libz-dev tcl8.6-dev python3-venv dh-systemd htop

sudo apt-get install tcl-dev autoconf python-dev python-virtualenv libz-dev tcl-dev  dh-systemd 
cd
git clone https://github.com/flightaware/piaware_builder.git
cd piaware_builder
./sensible-build.sh jessie
cd ..
sudo dpkg -i piaware_3.1_armhf.deb   (or whatever the .deb filename is )

**Comment by J-Luc16** [comment]
Hi,

Thanks a lot. In fact, all the Piaware part of the package have well passed trough the Ubuntu 15 to 16 upgrade, **still working perfectly** (ADSB + fa mlat). But the "mlat client" which I use in association with a VirtualRadar platform operating mlat server does not, 

My problem is that even if setup.py has put mlat-client in /usr/bin, configuration kept from Ubuntu 15 on which is works, , /etc/init.d script unchanged,  but mlat-client does not operate.

Excuse me if it's not clear, english is not my main language :-)

J-Luc

**Comment by J-Luc16** [comment]
Problem solved. I have rebuilt the package myself, following your instructions.

My Piaware is now under Xenial.

J-Luc
