### ISSUE TITLE
Error v0.2.7

### ISSUE THREAD

**Issue by Chrisoo** [mutability/mlat-client#16]
I updated to version 0.2.7 and shows this error:
**Fri Jan  6 18:57:17 2017 mlat-client 0.2.7 starting up
Traceback (most recent call last):
  File "/usr/bin/mlat-client", line 101, in <module>
    main()
  File "/usr/bin/mlat-client", line 95, in main
    coordinator = Coordinator(receiver=receiver, server=server, outputs=outputs, freq=options.clock_frequency(args))
TypeError: __init__() missing 1 required positional argument: 'allow_anon'**

**Comment by mutability** [comment]
You have a mismatch in your installed client vs. the associated packages; the code you quote is not in 0.2.7

**Comment by mutability** [comment]
specifically, see https://github.com/mutability/mlat-client/blob/v0.2.7/mlat-client#L95

**Comment by Chrisoo** [comment]
Ok, I worked it out with the previous problem.
Now I have a problem with the mlat-client, does not want to connect with the receiver (--input-connect).

mlat-client:
```
Fri Jan  6 22:23:38 2017 mlat-client 0.2.7 starting up
Fri Jan  6 22:23:38 2017 Connected to multilateration server at localhost:33031, handshaking
Fri Jan  6 22:24:38 2017 Disconnecting from localhost:33031: No data (not even keepalives) received for 60 seconds
Fri Jan  6 22:24:38 2017 Connected to multilateration server at localhost:33031, handshaking
Fri Jan  6 22:25:38 2017 Disconnecting from localhost:33031: No data (not even keepalives) received for 60 seconds
```
On mlat-server error:
```
20170106 22:18:20.175  ERROR    asyncio              Exception in callback StreamReaderProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>)
handle: <Handle StreamReaderProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/streams.py", line 225, in connection_made
    self._stream_writer)
  File "/home/chriso/mlat-server/mlat/server/net.py", line 82, in start_client
    newclient = self._new_client(r, w)
  File "/home/chriso/mlat-server/mlat/server/jsonclient.py", line 76, in _new_client
    udp_port=self.udp_port)
  File "/home/chriso/mlat-server/mlat/server/jsonclient.py", line 173, in __init__
    self.host, self.port = self.transport.get_extra_info('peername')
ValueError: too many values to unpack (expected 2)
```
I would add, that the version 0.2.5dev works good.

**Comment by mutability** [comment]
Maybe ipv6.

**Comment by mutability** [comment]
Take a look at https://docs.python.org/3/library/socket.html#socket-families
You might need to teach the server about the 4-tuple IPv6 address format.

**Comment by Chrisoo** [comment]
I turned off IPv6 and now works.
Thanks
