### ISSUE TITLE
0.1.17 [Errno 105] ENOBUFS

### ISSUE THREAD

**Issue by jester-xbmc** [mutability/mlat-client#2]
I'm getting this after running for a while (< 24 hrs) mem leak ? or something else ?

Fri Jun 19 09:29:01 2015 Input connected to localhost:30005
Fri Jun 19 09:29:02 2015 Lost connection to localhost:30005
Fri Jun 19 09:29:02 2015 Reconnecting in 30.0 seconds
Fri Jun 19 09:29:32 2015 Connection to localhost:30005 failed: [Errno 105] ENOBUFS
Fri Jun 19 09:29:32 2015 Reconnecting in 30.0 seconds
Fri Jun 19 09:30:02 2015 Input connected to localhost:30005
Fri Jun 19 09:30:02 2015 Lost connection to localhost:30005
Fri Jun 19 09:30:02 2015 Reconnecting in 30.0 seconds

**Comment by mutability** [comment]
Resource leak. But it could be elsewhere in the system. Try restarting just mlat-client; if that does not help, then it's a leak elsewhere in the system.
