### ISSUE TITLE
Receiver set to type Beast will not show sync with Rx type Radarcape.

### ISSUE THREAD

**Issue by marcus-aa** [mutability/mlat-client#23]
An actual beast, set to `--input-type beast`, will never **_show_** sync stats towards receivers of type `radarcape`. If set to `dump1090`, it will show sync.

The log file indicates that the receiver pair is used for solutions, so it actually has sync, but not shown in the sync stats table.

If 2 dump1090 system are both set to `--input-type beast` (for testing this issue, or by mistake), they will also not show sync with radarcapes, not with real beast systems, and not with each other, but with normal dump1090 systems....

(The client will auto-detect the correct format but has already informed the server of the manually set format, and as discussed, the on-the-fly format change is not implemented in mlat-server. )

What is the difference between beast and dump input formats?

**Comment by mutability** [comment]
This sounds like a server-side issue?

**Comment by marcus-aa** [comment]
Quite possible. It changes behaviour with `--input-type` in the client, but may very well be all in the server code.

Should I move it to the server issues?

**Comment by mutability** [comment]
Well, without a specific bug report about the client misbehaving, there's not much to be done in the client side. On the server side, unfortunately I have about zero spare time to look at it.

**Comment by mutability** [comment]
(this is probably just another case of the server code not understanding the client clock changes)

**Comment by marcus-aa** [comment]
I know. I'll document it there anyway.
