### ISSUE TITLE
Copy of input stream to another server

### ISSUE THREAD

**Issue by bilbolodz** [mutability/mlat-client#28]
Is it possible to add option to copy incoming stream from receiver to another server? It could be useful if you want feed mlat-server and running another visualization software (e.x. Virtual Radar Server) from the same receiver. Of course duplication of traffic could be done at VRS but unfortunately these software is a little unstable while serving more receivers/user/traffic. Now I'm using modesmixer to duplicate traffic stream but i require one another modesmixer process per receiver......

**Comment by VA2XJM** [comment]
You should check for Beast-Splitter: https://github.com/flightaware/beast-splitter

You can use it to take the feed from the receiver or from your dump1090 instance and push it to another software OR to listen for connections from other software.

Ex: ./beast-splitter --net Receiver-IP:Port --connect Dump1090-ip:port --listen port-for-VRS

the --net connects to your receiver OR your dump1090 depending on your setup. --connect will connect on the ip/port you specify and push the data. --listen will push the data when another software will connect to this one.

You should never use VRS to feed MLAT. MLAT client is designed to feed MLAT server without needing to install more than Dump1090, d1090 can accept more than one connection...

**Comment by bilbolodz** [comment]
I can use modesmixer also but that NOT a point. I'm running "private ADSB server" with at least 100 active receivers. I want one connection from receiver to "my software" (configuring more connection is beyond scope of "normal user". So now I've (sorry for ascii art):

                                                 ---> mlat-client -> mlat-server --------
                                                 |                                                        |
user receiver -> modesmixer -----------------------------------------------VRS 

(actually there is one more modesmixer which collects data from "all other modesmixers" and put it into VRS) but 100 user receivers means 100x modesmixer and 100x mlat-client.... 100x mlat-client it's a must but if mlat-client would have option to "copy raw traffic" I would can remove 100 modesmixer processes and feed VRS from mlat-client directly (throught one modesmixer collector but that's not a point). When you have 5 to 10 receivers running a few additional processes it's not a problem but when you have 100 or 200 receivers it becomes to be a problem.
Is it clear now?

**Comment by mutability** [comment]
I don't think this belongs in mlat-client. Either connect directly to dump1090 (as mentioned above, it supports multiple connections) or, if you have a device that only supports a single connection e.g. a Mode S Beast on a serial port, then use beast-splitter.

In particular, mlat-client goes to a lot of effort to filter the messages it needs to process, as the Python side of processing is fairly slow. Copying all messages to a separate port would defeat this filtering.

**Comment by VA2XJM** [comment]
on the user end it must be: 
Dump1090 -> (MLAT Client -> MLAT Server) + Beast-Splitter (Taking Dump1090 and pushing it to your own dump1090 instance on your server)

On your server:
MLAT-Client -> MLAT Server
Beast-splitter connection -> Dump1090 --net-only that you use as your hub aggregate your data... then VRS will connect to your local Dump1090 instance...

**Comment by VA2XJM** [comment]
A simple bash script can also use SoCat to start the MLAT-Client and redirect traffic to your aggregator at once...

**Comment by bilbolodz** [comment]
OK. Your software, your time, your rules but please think about scale. 10 receivers - not a problem. 200 receivers it's 200 more processes 400 more open files etc.

**Comment by mutability** [comment]
I manage a network of 18000 receivers built around this; it scales just fine.

Going to close this as it's not something that belongs in mlat-client.

**Comment by bilbolodz** [comment]
OK
