### ISSUE TITLE
dpkg-buildpackage error - GPG key missing

### ISSUE THREAD

**Issue by saltthefries** [mutability/mlat-client#3]
I get the following error when using dpkg-buildpackage -b

```
gpg: skipped "Oliver Jowett <oliver@mutability.co.uk>": secret key not available
gpg: dpkg-sign.si23HyZP/mlat-client_0.2.1_armhf.changes: clearsign failed: secret key not available

dpkg-buildpackage: error: failed to sign .changes file
```

I think the Debian package build instructions should be to use dpkg-buildpackage -b -uc for an unsigned .changes file, or to replace the GPG key. Would you like me to submit a pull request?

**Comment by mutability** [comment]
That's only a warning on my system..

**Comment by saltthefries** [comment]
Sorry--I retested this and I'm now seeing that the dpkg-buildpackage message does not prevent the creation of a package. Closing this.

**Comment by mutability** [comment]
It's still a sensible thing to do..
