### ISSUE TITLE
where is the input？

### ISSUE THREAD

**Issue by GreenScarf** [mutability/mlat-client#30]
Excuse me,I have read the client code，but i have not found the code that  connectint the input host:post.
it means i dont know the mode S report how to input the client.

**Comment by mutability** [comment]
See https://github.com/mutability/mlat-client/blob/master/mlat/client/net.py#L43 and https://github.com/mutability/mlat-client/blob/master/mlat/client/receiver.py#L33

**Comment by GreenScarf** [comment]
thank you for your reply. the function :start.server() has been called in https://github.com/mutability/mlat-client/blob/59e3d57ec0772d0dc5d7cde5a02130548a584840/mlat-client#L98 .then,we jump to https://github.com/mutability/mlat-client/blob/59e3d57ec0772d0dc5d7cde5a02130548a584840/mlat/client/jsonclient.py#L193 call self.reconnect(),so the socket to server has been created. but i havent found the receiver.start(),i means the receiving thread is no start.
so my confusion is that i have found the code to start the server,but i have not found the code to start the receiver, the socket to input is not created.

**Comment by mutability** [comment]
https://github.com/mutability/mlat-client/blob/59e3d57ec0772d0dc5d7cde5a02130548a584840/mlat/client/coordinator.py#L235

**Comment by GreenScarf** [comment]
i got it. thank you sincerely.
