### ISSUE TITLE
Error "options"

### ISSUE THREAD

**Issue by Chrisoo** [mutability/mlat-client#4]
After update mlat-client v0.2.2 an error:
ImportError: cannot import name options
from mlat.client import options

**Comment by mutability** [comment]
How did you install the new version?

**Comment by Chrisoo** [comment]
"Installation - Raspbian"
or
"Installing - other Debian-like systems"

**Comment by mutability** [comment]
OK - so you built the package yourself and then installed it?
What OS/version are you installing on?

**Comment by Chrisoo** [comment]
Yes, built the package also installed.
OS: Linux raspberrypi 3.18.11-v7+ #781

**Comment by mutability** [comment]
OK. Can you try reinstalling using standard package then, as I don't see this problem with the standard package at all.

$ wget http://repo.mutability.co.uk/raspbian/pool/rpi/m/mlat-client/mlat-client_0.2.2_armhf.deb
$ sudo dpkg -i mlat-client_0.2.2_armhf.deb

**Comment by Chrisoo** [comment]
This is the same.
In file /var/log/mlat-client.log:
Traceback (most recent call last):
  File "/usr/bin/mlat-client", line 28, in <module>
    from mlat.client import options
ImportError: cannot import name options

**Comment by mutability** [comment]
OK. You have something else interfering with your install then, maybe a stray install you did by hand.

Try this and attach the output?

```
$ python3 -c "import mlat.client; print(mlat.client.__file__)"
/usr/lib/python3/dist-packages/mlat/client/__init__.py
```

**Comment by Chrisoo** [comment]
/usr/lib/python3.2/mlat/client/**init**.py

**Comment by mutability** [comment]
That is an old installation that you must have done by hand at some point. Remove everything under /usr/lib/python3.2/mlat

**Comment by Chrisoo** [comment]
OK, now it works well :+1: 
Thanks
