### ISSUE TITLE
Full path to fa-mlat-client is displayed incorrectly. 

### ISSUE THREAD

**Issue by dschaper** [mutability/mlat-client#5]
Cosmetic fix only. (And not sure if this is a piaware issue or mlat-client issue)

Running `ps ax` displays `/usr/bin/python3 /usr/sbin/fa-mlat-client` but the client is actually located in `/usr/bin` 

`locate fa-mlat-client`
`/usr/bin/fa-mlat-client`

**Comment by dschaper** [comment]
Looks like this is a piaware issue. Closing.

**Comment by mutability** [comment]
I can't see how this would possibly happen with either mlat-client or piaware. fwiw.

**Comment by dschaper** [comment]
I don't either, unless there is something in tcllauncher?

**Comment by mutability** [comment]
tcllauncher is only used for the tcl bits, fa-mlat-client is python not tcl
