### ISSUE TITLE
ZeroDivisionError thrown from stats log_and_reset() when receiver_rx_messages is zero

### ISSUE THREAD

**Issue by Chrisoo** [mutability/mlat-client#8]
Now, as no data is transmitted it is several attempts (probably 5) connections and disables definitely "mlat-client". Previously, all the time trying to connect until manually turned off it. Could she come back in this feature?

**Comment by mutability** [comment]
I'm not sure what you're saying here; can you explain another way? or provide logs?

**Comment by Chrisoo** [comment]
http://screenshot.sh/mLK9Ubwgjk4bc 
and so once I tried to connect to was non-stop.
Now it turns off after a few attempts the connection (probably 5).
I have several remote clients who do not send the whole time data only include time to time and I would like to "mlat-client" still try to connect non-stop.

**Comment by mutability** [comment]
That log looks OK. Can you show me the logs after it has stopped working?

**Comment by Chrisoo** [comment]
http://screenshot.sh/mE1xRJUg5y3J6

**Comment by mutability** [comment]
Ok, thanks, that shows me the real problem (ZeroDivisionError thrown from stats when receiver_rx_messages is zero)

**Comment by Chrisoo** [comment]
Thanks
