### ISSUE TITLE
"--results" all position

### ISSUE THREAD

**Issue by Chrisoo** [mutability/mlat-client#9]
Is it possible in the results display all aircraft position generated by the mlat-server?

**Comment by mutability** [comment]
No; you need to do that on the server itself.

**Comment by Chrisoo** [comment]
Ok, and that the results from the server has access only user who has enabled mlat-client?
Because now it is that everyone has access to these results from the mlat-server.

**Comment by mutability** [comment]
I don't understand what you are asking.

**Comment by Chrisoo** [comment]
Now it is that everyone has access to these all receiver results from the mlat-server (if you know the IP server).
Do these results may have a user who has enabled the mlat-client?

**Comment by mutability** [comment]
I still don't understand what you're asking, sorry.

Let me explain how the client results work:

The server receives messages from some clients and computes a position from those messages.
It sends that position to two places:
- It sends them to whatever you have configured on the server. For example, anything configured with --basestation-listen / --basestation-connect / --write-csv. This receives _all positions_.
- It sends them to the clients that provided the messages that were used to find the position. So clients receive only positions that they contributed to. They do not receive all positions. Each client can then generate results locally in various ways based on what they pass to --results.

If you want to restrict who can access the position results configured on the server, you should use the normal tools for restricting access to those network ports - for example, a firewall, or use the *-connect options not the *-listen options to avoid opening a listening port.

If you want to restrict what results are sent to individual clients, you will need to edit the server source code to disable what is sent there.

**Comment by Chrisoo** [comment]
Thanks for the clarification. 
Now I know that you can not do that with what I asked. 
:-(
